### ISSUE TITLE
percentages not calculating correctly

### ISSUE THREAD

**Issue by KRuggles** [KGrafton86/LabradorCoatColors#1]
Per the results of test_all_mating_pairs.py, some calculations are not coming out to 100%

Example: 
Test 729 of 729

SIRE: - bbEedd - silver
DAM: - bbEedd - silver

POTENTIAL OFFSPRING GENOTYPES: 
[('bbeedd', 16, 25.0), ('bbEEdd', 16, 25.0), ('bbEedd', 32, 50.0)]

POTENTIAL OFFSPRING PHENOTYPES: 
[('silver', 48, 75.0)]

**Comment by KGrafton86** [comment]
For 144 of the 729 potential mating pairs, the phenotype percentage is not summing to 100%. It is not immediately obvious any pattern of genotypes/colors/etc. that it relates to.

[test_all_mating_pairs_results_filtered.xlsx](https://github.com/KGrafton86/LabradorCoatColors/files/6527476/test_all_mating_pairs_results_filtered.xlsx)

**Comment by KGrafton86** [comment]
The "liver pigment" note on certain genotypes was causing the issue, it was being skipped when counting yellow & champagne. Commented out that section of code since it isn't really necessary, and it works properly.
